---
id: ingo
name: Ingo
full: Email filter rules manager application
description: >-
  Ingo is an email-filter management application. It is fully internationalized,
  integrated with Horde and the IMP Webmail client, and supports both
  server-side (Sieve, Procmail, Maildrop) and client-side (IMAP) message
  filtering.
list: ~
type: application
homepage: https://www.horde.org/apps/ingo
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 4.0.0alpha6
  api: 4.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: ASL
  uri: http://www.horde.org/licenses/apache
dependencies:
  required:
    php: ^7.4 || ^8
    composer:
      horde/horde: ^6
      horde/auth: ^3
      horde/autoloader: ^3
      horde/core: ^3
      horde/exception: ^3
      horde/group: ^3
      horde/form: ^3
      horde/imap_client: ^3
      horde/managesieve: ^2
      horde/mime: ^3
      horde/perms: ^3
      horde/share: ^3
      horde/util: ^3
      horde/view: ^3
    ext:
      gettext: '*'
  optional:
    composer:
      horde/listheaders: ^2
      horde/mongo: ^2
      horde/vfs: ^3
