---
id: ingo
name: Ingo
full: Email filter rules manager application
description: >-
  Ingo is an email-filter management application. It is fully internationalized,
  integrated with Horde and the IMP Webmail client, and supports both
  server-side (Sieve, Procmail, Maildrop) and client-side (IMAP) message
  filtering.
list: ~
type: application
homepage: https://www.horde.org/apps/ingo
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 4.0.0alpha1
  api: 4.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: ASL
  uri: http://www.horde.org/licenses/apache
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/horde: ^5
      pear.horde.org/Horde_Auth: ^2
      pear.horde.org/Horde_Autoloader: ^2
      pear.horde.org/Horde_Core: ^2.12
      pear.horde.org/Horde_Exception: ^2
      pear.horde.org/Horde_Group: ^2
      pear.horde.org/Horde_Form: ^2
      pear.horde.org/Horde_Imap_Client: ^2
      pear.horde.org/Horde_Mime: ^2.5
      pear.horde.org/Horde_Perms: ^2
      pear.horde.org/Horde_Share: ^2
      pear.horde.org/Horde_Util: ^2
      pear.horde.org/Horde_View: ^2
    ext:
      gettext: '*'
  optional:
    pear:
      pear.horde.org/Horde_ListHeaders: ^1
      pear.horde.org/Horde_ManageSieve: ^1
      pear.horde.org/Horde_Mongo: ^1
      pear.horde.org/Horde_Vfs: ^2
