<?php
// ADMINISTRATORS: Do not edit this file. Put custom routes into var/config/ingo/routes.local.php and run composer horde:reconfigure
namespace Horde\Ingo;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;

// Responsive UI Routes
$mapper->connect(
    'ResponsiveRules',
    '/responsive',
    [
        'controller' => Responsive\ResponsiveController::class,
        'HordeAuthType' => 'authenticate',
        'stack' => [],
    ]
);

$mapper->connect(
    'ResponsiveRule',
    '/responsive/rule/:uid',
    [
        'controller' => Responsive\ResponsiveController::class,
        'HordeAuthType' => 'authenticate',
        'stack' => [],
    ]
);
