<?php

// ADMINISTRATORS: Do not edit this file. Put custom routes into var/config/ingo/routes.local.php and run composer horde:reconfigure

namespace Horde\Ingo;

use Horde\Core\Middleware\DefaultStack;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;

// Responsive UI Routes - PSR-style builder pattern

// Responsive Rules Index - Primary route with legacy smartmobile secondary
$mapper->buildRoute(uri: '/responsive', name: 'ResponsiveRules')
    ->withController(Responsive\ResponsiveController::class)
    ->withDefaults(['HordeAuthType' => 'authenticate'])
    ->withMiddleware(DefaultStack::get())
    ->withSecondaryRoute('/smartmobile')
    ->withSecondaryRoute('/smartmobile.php')
    ->add();

// Responsive Rule View - View single rule by UID
$mapper->buildRoute(uri: '/responsive/rule/:uid', name: 'ResponsiveRule')
    ->withController(Responsive\ResponsiveController::class)
    ->withDefaults(['HordeAuthType' => 'authenticate'])
    ->requires('uid', '[a-zA-Z0-9\-_]+')
    ->withMiddleware(DefaultStack::get())
    ->add();
